# vim: ft=yaml.ansible
---
- name: Main play
  hosts: 127.0.0.1
  connection: local
  collections:
    - kewlfft.aur.aur
  vars:
    desktop: hyprland
    intercept_dev: framework
  roles:
    - core
    - display_server
    - workstation
    - de_wm
    - user
    - laptop
    - smb_share
    - interception
    - bluetooth

  tasks:
    - name: Install neovim-nightly
      kewlfft.aur.aur:
        use: yay
        name:
          - neovim-nightly-bin
