# vim: ft=yaml.ansible
---
- name: Set HOSTNAME variable at system level
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^HOSTNAME="
    line: HOSTNAME=$(uname -n)
  become: true

- name: Set timezone to US Central
  community.general.timezone:
    name: America/Chicago

- name: Install packages
  community.general.pacman:
    name:
      - base
      - base-devel
      - bat
      - bind
      - btop
      - efibootmgr
      - fd
      - fzf
      - git
      - htop
      - keychain
      - libfido2
      - man-db
      - man-pages
      - openssh
      - pacman-contrib
      - reflector
      - ripgrep
      - starship
      - stow
      - sudo
      - tldr
      - tree
      - tmux
      - unzip
      - usbutils
      - vi
      - vim
      - wget
      - xdg-desktop-portal
      - xdg-utils
      - xterm
      - zip
      - zsh
    state: present
  become: true

- name: Start systemd service - systemd-modules-load.service
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    state: started
    enabled: true
  become: true

- name: Start systemd service - systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  become: true

- name: Start systemd service - paccache.timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: true
  become: true

- name: Update reflector configuration file
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable systemd service - reflector.service
  ansible.builtin.systemd:
    name: reflector.service
    enabled: true
  become: true

- name: Start systemd service - reflector.timer
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: true
  become: true

- name: Update pacman configuration file
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start systemd service - systemd-boot-update.service
  ansible.builtin.systemd:
    name: systemd-boot-update.service
    state: started
    enabled: true
  become: true

- name: Upgrade system
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true
