---
- name: Create 'aur_builder' user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow 'aur_builder' to run 'sudo pacman' without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: 0644
    validate: "visudo -cf %s"

- name: Installing AUR helper
  kewlfft.aur.aur:
    name: yay
