---
- name: Install power management packages
  community.general.pacman:
    name:
      - power-profiles-daemon
      - brightnessctl
      - powertop
    state: present
  become: true

- name: Start systemd service - power-profiles-daemon.service
  ansible.builtin.systemd:
    name: power-profiles-daemon.service
    state: started
    enabled: yes
  become: true
