---
- name: Install power management packages
  community.general.pacman:
    name:
      - brightnessctl
      - powertop
    state: present
  become: true

- name: Suspend/hibernate boilerplate
  ansible.builtin.import_tasks: sleep.yml
