---
- name: Create drop-in for logind conf
  ansible.builtin.copy:
    src: ../templates/logind.conf
    dest: /etc/systemd/logind.conf.d/logind.conf
    backup: no
    force: false
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create drop-in for sleep conf
  ansible.builtin.copy:
    src: ../templates/sleep.conf
    dest: /etc/systemd/sleep.conf.d/sleep.conf
    backup: no
    force: false
    owner: root
    group: root
    mode: 0644
  become: true
