# vim: ft=yaml.ansible
---
- name: KVM | Select ethernet interface name
  ansible.builtin.set_fact:
    bridge_slave: "{{ ansible_interfaces | select('match', '^en') | first }}"

- name: KVM | When compatible interface is present, create bridge and add bridge_slave to bridge
  when: bridge_slave | length > 0
  block:
    - name: KVM | Create NetworkManager bridge network
      community.general.nmcli:
        type: bridge
        conn_name: br0
        method4: auto
        method6: disabled
        state: present
        stp: false

    - name: KVM | Add bridge_slave interface to bridge
      nmcli:
        type: ethernet
        slave_type: bridge
        conn_name: "{{ item }}"
        state: present
        master: br0
      with_items: "{{ bridge_slave }}"
