# vim: ft=yaml.ansible
---
- name: Install power management packages
  community.general.pacman:
    name:
      - solaar
    state: present
  become: true

- name: Create drop-in for Solaar on Wayland
  ansible.builtin.copy:
    src: 42-logitech-unify-permissions.rules
    dest: /etc/udev/rules.d/42-logitech-unify-permissions.rules
    backup: false
    force: false
    owner: root
    group: root
    mode: "0644"
  become: true
