# vim: ft=yaml.ansible
---
- name: Install interception-caps2esc
  community.general.pacman:
    name:
      - interception-caps2esc
    state: present
  become: true

- name: Add caps2esc config for Framework laptop keyboard
  when: intercept_dev == "framework"
  block:
    - name: Create caps2esc rule for Framework
      ansible.builtin.template:
        src: framework.yaml.j2
        dest: /etc/interception/udevmon.d/framework.yaml
        backup: true
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Enable udevmon service and make sure it's started
      ansible.builtin.systemd_service:
        name: udevmon
        enabled: true
        state: started
      become: true
