# vim: ft=yaml.ansible
- name: Mount Backup SMB share
  ansible.posix.mount:
    src: //debsrv01/Backup
    path: /mnt/nas/backup
    opts: "guest,x-systemd.automount,iocharset=utf8,file_mode=0777,dir_mode=0777"
    fstype: cifs
    state: mounted
  become: true

- name: Mount Media SMB share
  ansible.posix.mount:
    src: //debsrv01/Media
    path: /mnt/nas/media
    opts: "guest,x-systemd.automount,iocharset=utf8,file_mode=0777,dir_mode=0777"
    fstype: cifs
    state: mounted
  become: true
